optimizer : {
  type: AdamW,
  kwargs: {
  #lr : 0.01,
  lr : 0.01,
  weight_decay : 0.05
}}

scheduler: {
  type: function,    
}

dataset : {
  train : { _base_: cfgs/dataset_configs/ModelNet40.yaml, 
            others: {subset: 'train'}},
  val : { _base_: cfgs/dataset_configs/ModelNet40.yaml,
            others: {subset: 'test'}},
  test : { _base_: cfgs/dataset_configs/ModelNet40.yaml,        
            others: {subset: 'test'}}}   
model : {
  #NAME: DGCNN_cls,
  #NAME: PointNet,
  NAME: Point_MAE,       
  #NAME: DGCNN_cls,  
  #NAME: DGCNN_cls,      
  #NAME: DGCNN_cls,   
  # NAME: CurveNet, 
  #NAME: PointNet_rotnet, 
  group_size: 32,  
  num_group: 64,      
  loss: cdl2,
  num_hid_cls_layers: 2,       
  group_norm: False,
  regularize : False, 

  #### Added by Ali Network 
  k: 20,  
  emb_dims: 1024,
  dropout: 0.5, 

  transformer_config: { 
    mask_ratio: 0.9,
    mask_type: 'rand',
    trans_dim: 384, 
    encoder_dims: 384,    
    depth: 12,   
    drop_path_rate: 0.1, 
    num_heads: 6,   
    decoder_depth: 4,
    decoder_num_heads: 6,   
    dataset_name: "modelnet",


    #### Added by Ali
    method: Tent_WA_FPS,                       ### Tent_Modified ,    Tent_WA_FPS: our method      
    reset: True,            
    parallel_mode: True,   
    loss_encoder: "MSE",                         
    N_Aug: 6,        
    Type_Aug: "jitter",                                                              
    batch_size: 128,                                           
    iteration: 1,                
    original: True,                           ### default: True
    cross_entropy: False,                                              
    layer_norm: True,                         ### if True, batch norms and layer norms are updated. Just PointMAE has Batch Norm and Layer Norm. Other networks just have Batch Norm.                             
  },
  }  

 
npoints: 1024      
npoints_ours: 512                        
total_bs : 32     
step_per_update : 1
max_epoch : 1
grad_norm_clip : 10
tta_dataset_path : '/export/livia/home/vision/Abahri/projects/MATE/MATE/data/tta_datasets' 
normal : False
